import itertools

# ==========================================
# 1. 定义辅助函数 (必须在任何调用之前定义)
# ==========================================
def extended_gcd(a, b):
    if a == 0:
        return b, 0, 1
    gcd, x1, y1 = extended_gcd(b % a, a)
    x = y1 - (b // a) * x1
    y = x1
    return gcd, x, y

def mod_inverse(a, m):
    gcd, x, y = extended_gcd(a % m, m)
    if gcd != 1:
        return None
    else:
        return (x % m + m) % m

# ==========================================
# 2. 定义模数
# ==========================================
mods = [64, 63, 65, 31, 29, 23, 19, 17, 11]
n = len(mods)

# ==========================================
# 3. 生成所有组合 C(9,3)
# ==========================================
combinations = list(itertools.combinations(range(n), 3))
print(f"// --- Auto-generated RRNS Parameters Arrays ---")
print(f"// --- Total Combinations: {len(combinations)} ---")

# ==========================================
# 4. 准备数据列表
# ==========================================
mi0_vals = []
mi1_vals = []
mi2_vals = []
inv0_vals = []
inv1_vals = []
inv2_vals = []
m_total_vals = []
idx1_vals = []
idx2_vals = []
idx3_vals = []

# ==========================================
# 5. 计算并填充列表
# ==========================================
for idx, (i, j, k) in enumerate(combinations):
    m1, m2, m3 = mods[i], mods[j], mods[k]
    
    # 计算 Mi (其他两个模数的乘积)
    Mi1 = m2 * m3
    Mi2 = m1 * m3
    Mi3 = m1 * m2
    
    # 计算总模数
    M_total = m1 * m2 * m3
    
    # 计算模逆元
    inv1 = mod_inverse(Mi1 % m1, m1)
    inv2 = mod_inverse(Mi2 % m2, m2)
    inv3 = mod_inverse(Mi3 % m3, m3)
    
    # 安全检查
    if None in [inv1, inv2, inv3]:
        raise ValueError(f"Inverse calculation error for combination {idx}: ({m1}, {m2}, {m3})")

    # 添加到列表 (注意格式化为 Verilog 数字格式)
    mi0_vals.append(f"20'd{Mi1}")
    mi1_vals.append(f"20'd{Mi2}")
    mi2_vals.append(f"20'd{Mi3}")
    
    inv0_vals.append(f"20'd{inv1}")
    inv1_vals.append(f"20'd{inv2}")
    inv2_vals.append(f"20'd{inv3}")
    
    m_total_vals.append(f"20'd{M_total}")
    
    idx1_vals.append(f"4'd{i}")
    idx2_vals.append(f"4'd{j}")
    idx3_vals.append(f"4'd{k}")

# ==========================================
# 6. 写入文件
# ==========================================
output_filename = 'rrns_params_array.v'

with open(output_filename, 'w') as f:
    f.write("// --- Auto-generated RRNS Parameters Arrays ---\n")
    f.write("// Generated by 3nrm_gen_params_array.py\n")
    f.write("`define NUM_CHANNELS 84\n\n")
    
    # 辅助函数用于格式化输出
    def write_array(f, name, data_list):
        f.write(f"localparam [19:0] {name} [0:83] = '{{\n")
        # 每行写 4 个数据，方便阅读
        for i in range(0, len(data_list), 4):
            chunk = data_list[i:i+4]
            line = "    " + ", ".join(chunk)
            if i + 4 < len(data_list):
                line += ","
            f.write(line + "\n")
        f.write("};\n\n")

    # 写入各个数组
    # 注意：Verilog packed array 初始化语法
    write_array(f, "PARAM_MI0", mi0_vals)
    write_array(f, "PARAM_MI1", mi1_vals)
    write_array(f, "PARAM_MI2", mi2_vals)
    
    write_array(f, "PARAM_INV0", inv0_vals)
    write_array(f, "PARAM_INV1", inv1_vals)
    write_array(f, "PARAM_INV2", inv2_vals)
    
    write_array(f, "PARAM_M_TOTAL", m_total_vals)
    
    # 索引数组位宽较小，单独处理格式 (虽然上面统一用了20d，这里为了严谨可以改，但为了代码简单先统一用20d存储，使用时会自动截断)
    # 为了更精准，我们重新格式化一下索引数组为 4'd
    idx1_fmt = [f"4'd{i}" for i in [int(x.split("'d")[1]) for x in idx1_vals]]
    idx2_fmt = [f"4'd{i}" for i in [int(x.split("'d")[1]) for x in idx2_vals]]
    idx3_fmt = [f"4'd{i}" for i in [int(x.split("'d")[1]) for x in idx3_vals]]
    
    # 覆盖写入函数以支持不同位宽声明
    def write_array_custom_width(f, name, data_list, width):
        f.write(f"localparam [{width-1}:0] {name} [0:83] = '{{\n")
        for i in range(0, len(data_list), 4):
            chunk = data_list[i:i+4]
            line = "    " + ", ".join(chunk)
            if i + 4 < len(data_list):
                line += ","
            f.write(line + "\n")
        f.write("};\n\n")

    write_array_custom_width(f, "PARAM_IDX1", idx1_fmt, 4)
    write_array_custom_width(f, "PARAM_IDX2", idx2_fmt, 4)
    write_array_custom_width(f, "PARAM_IDX3", idx3_fmt, 4)

print(f"✅ 成功！参数已生成到 '{output_filename}'")
print(f"   请将此文件复制到 Vivado 项目目录，并在 decoder_3nrm_mld.v 中通过 `include 引入。")